Generate the documentation via templates
Rather than generating the documentation via Antora extension at website
build time, this generates the documentation using golang templates at
build time.

Reference: EC-513

diff --git a/.github/workflows/pre-merge-ci.yaml b/.github/workflows/pre-merge-ci.yaml
--- a/.github/workflows/pre-merge-ci.yaml
+++ b/.github/workflows/pre-merge-ci.yaml
@@ -20,11 +20,11 @@ name: pre-merge-ci
 on:
   pull_request:
     branches:
-    - main
+      - main
 
   push:
     branches:
-    - main
+      - main
 
   workflow_dispatch:
 
@@ -35,30 +35,39 @@ jobs:
   all-tests-and-checks:
     runs-on: ubuntu-latest
     steps:
-    - name: Harden Runner
-      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
-      with:
-        egress-policy: audit
-        disable-telemetry: true
+      - name: Harden Runner
+        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
+        with:
+          egress-policy: audit
+          disable-telemetry: true
 
-    - name: Checkout code
-      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
+      - name: Checkout code
+        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
 
-    - name: Setup Go environment
-      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
-      with:
-        go-version-file: go.mod
-        cache: true
+      - name: Setup Go environment
+        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
+        with:
+          go-version-file: go.mod
+          cache: true
 
-    - name: Run checks
-      run: make ci
+      - name: Run checks
+        run: make ci
 
-    # See https://issues.redhat.com/browse/HACBS-2391 to re-enable these checks
-    # - name: Validate added bundles
-    #   run: ./hack/validate-acceptable-bundles.sh
+      - name: Check for uncommitted changes
+        run: |
+          if ! git diff --exit-code -s; then
+            for f in $(git diff --exit-code --name-only); do
+              echo "::error file=$f,line=1,col=1,endColumn=1::File was modified in build"
+            done
+            exit 1
+          fi
 
-    - name: Upload test coverage report
-      uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
-      if: always()
-      env:
-        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      # See https://issues.redhat.com/browse/HACBS-2391 to re-enable these checks
+      # - name: Validate added bundles
+      #   run: ./hack/validate-acceptable-bundles.sh
+
+      - name: Upload test coverage report
+        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
+        if: always()
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
